Import libraries

In [1]:
import re
import os
import pandas as pd
import numpy as np

In [2]:
import stata_setup
stata_setup.config(os.path.join('/', 'Applications', 'Stata'), 'se')
from pystata import stata

  ___  ____  ____  ____  ____ ®
 /__    /   ____/   /   ____/      18.0
___/   /   /___/   /   /___/       SE—Standard Edition

 Statistics and Data Science       Copyright 1985-2023 StataCorp LLC
                                   StataCorp
                                   4905 Lakeway Drive
                                   College Station, Texas 77845 USA
                                   800-STATA-PC        https://www.stata.com
                                   979-696-4600        stata@stata.com

Stata license: Unlimited-user network, expiring 13 Dec 2025
Serial number: 401809347100
  Licensed to: Diana Tagliaferri


Notes:
      1. Unicode is supported; see help unicode_advice.
      2. Maximum number of variables is set to 5,000 but can be increased;
          see help set_maxvar.

Set directory

In [3]:
cd = os.getcwd()
print(cd)

/Users/dianatagliaferri/Library/CloudStorage/OneDrive-LondonBusinessSchool/Documents/Econometrics I/ps2

**Problem 1a**

Read the dataset and perform the required manipulations

In [4]:
# Read the dataset
ps1small = pd.read_csv(os.path.join(cd, 'ps1small.csv'))

# Add the log wage
old_cols = ps1small.columns.tolist()
display(ps1small[ps1small['wage'] <= 0]) # Check that 'wage' is always positive
ps1small['log_wage'] = np.log(ps1small['wage'])
ps1small = ps1small[['log_wage'] + old_cols].copy()

# Create interaction dummies between education and age
display(ps1small[['education', 'age']].dtypes) # Check data types
edu_levels = ps1small['education'].sort_values().unique().tolist()
age_levels = ps1small['age'].sort_values().unique().tolist()
combo_names = [f'{e}{a}' for e in edu_levels for a in age_levels]
edu_age_cat = pd.Categorical(
    ps1small['education'].astype(str) + ps1small['age'].astype(str),
    categories=combo_names
)
dummies = pd.get_dummies(edu_age_cat).astype(int)
dummies.columns = [f'd{col}' for col in dummies.columns]

# Concatenate dummies to the original dataframe
ps1small = pd.concat([ps1small, dummies], axis=1)
ps1small.head()

Empty DataFrame
Columns: [wage, education, age]
Index: []

education    int64
age          int64
dtype: object

,log_wage,wage,education,age,d1226,d1227,d1228,d1229,d1230,d1326,...,d1626,d1627,d1628,d1629,d1630,d1726,d1727,d1728,d1729,d1730
0,10.308953,30000,17,30,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,9.680344,16000,12,27,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,10.680516,43500,17,28,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,9.798127,18000,12,30,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,10.126631,25000,17,27,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

Regress lwage on the education-age dummies

In [6]:
stata.pdataframe_to_data(ps1small, force=True)

for dummy in dummies.columns:
    edu = dummy[1:3]
    age = dummy[3:]
    stata.run(f'label var {dummy}' + r' "I(\text{edu} = ' + edu + r', \text{age} = ' + age + ')"')

dummies_str = ' '.join(dummies.columns.tolist())

# Build dummy lists split into 3 chunks
parts = np.array_split(dummies.columns.tolist(), 3)
keep1, keep2, keep3 = [" ".join(p) for p in parts]

stata_code = f'''
capture ssc install outreg2
regress log_wage {dummies_str} , nocons

* Export the regression output in three separate fragments 
outreg2 using "p1a_1.tex", replace tex(fragment) label ctitle("lwage") dec(3) keep({keep1}) nonotes noobs nor2
outreg2 using "p1a_2.tex", replace tex(fragment) label ctitle("lwage") dec(3) keep({keep2}) 
outreg2 using "p1a_3.tex", replace tex(fragment) label ctitle("lwage") dec(3) keep({keep3}) nonotes noobs nor2
'''

stata.run(stata_code)

# Fix LaTeX output
subtables = []
for fname in ['p1a_1.tex', 'p1a_2.tex', 'p1a_3.tex']:
    with open(os.path.join(cd, fname), 'r') as f: 
        subtables.append(f.read().replace('VARIABLES', ''))
full_table = r'''
\begin{landscape}
\begin{table}[!htbp]\centering
\caption{Regression of lwage on dummies for education and age}
\label{tab:problem1a}

\begin{subtable}[t]{0.32\textwidth}\centering''' + '\n' + '\n'.join(subtables[0].splitlines()[:-2]) + '\n' + r'''
 & \\
 & \\
 & \\ \hline
 & \\
 & \\
\end{tabular}
\end{subtable}\hfill
\begin{subtable}[t]{0.32\textwidth}\centering''' + '\n' + subtables[1] + '\n' + r'''
\end{subtable}\hfill
\begin{subtable}[t]{0.32\textwidth}\centering''' + '\n' +'\n'.join(subtables[0].splitlines()[:-2]) + '\n' + r'''
 & \\
 & \\
 & \\ \hline
 & \\
 & \\
\end{tabular}
\end{subtable}

\end{table}
\end{landscape}
'''
full_table = re.sub(r'(?<!\$)(I\([^)]*\))(?!\$)', r'$\1$', full_table)
with open(os.path.join(cd, 'p1a.tex'), 'w') as f: f.write(full_table)
print(full_table)

.
. capture ssc install outreg2

. regress log_wage d1226 d1227 d1228 d1229 d1230 d1326 d1327 d1328 d1329 d1330
> d1426 d1427 d1428 d1429 d1430 d1526 d1527 d1528 d1529 d1530 d1626 d1627 d1628
>  d1629 d1630 d1726 d1727 d1728 d1729 d1730 , nocons

      Source |       SS           df       MS      Number of obs   =       898
-------------+----------------------------------   F(30, 868)      =   3960.93
       Model |  83238.0973        30  2774.60324   Prob > F        =    0.0000
    Residual |  608.027447       868   .70049245   R-squared       =    0.9927
-------------+----------------------------------   Adj R-squared   =    0.9925
       Total |  83846.1247       898  93.3698493   Root MSE        =    .83695

------------------------------------------------------------------------------
    log_wage | Coefficient  Std. err.      t    P>|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
       d1226 |    9.45132   .0907804   104.11   0.000     9.273145    9.629495
       d1227 |   9.300426   .0849798   109.44   0.000     9.133636    9.467216
       d1228 |   9.537856   .0832801   114.53   0.000     9.374402     9.70131
       d1229 |   9.385826   .0854213   109.88   0.000      9.21817    9.553483
       d1230 |   9.628323   .0877366   109.74   0.000     9.456122    9.800524
       d1326 |    9.61212   .1920105    50.06   0.000     9.235261     9.98898
       d1327 |   9.755901   .1920105    50.81   0.000     9.379042    10.13276
       d1328 |   9.378158    .174517    53.74   0.000     9.035633    9.720683
       d1329 |   9.819982   .2236854    43.90   0.000     9.380955    10.25901
       d1330 |   9.446488   .2029912    46.54   0.000     9.048077    9.844899
       d1426 |   9.580658   .2236854    42.83   0.000      9.14163    10.01969
       d1427 |   9.794423   .1708426    57.33   0.000      9.45911    10.12974
       d1428 |   9.642237   .2161007    44.62   0.000     9.218096    10.06638
       d1429 |   9.712199    .174517    55.65   0.000     9.369674    10.05472
       d1430 |    9.64544   .1708426    56.46   0.000     9.310127    9.980753
       d1526 |   9.534555   .2416079    39.46   0.000     9.060351    10.00876
       d1527 |   9.385619   .2321293    40.43   0.000     8.930019     9.84122
       d1528 |   9.573155   .2646682    36.17   0.000      9.05369    10.09262
       d1529 |   9.540361   .2523512    37.81   0.000     9.045071    10.03565
       d1530 |   9.919473   .2416079    41.06   0.000     9.445269    10.39368
       d1626 |    10.0705   .1673909    60.16   0.000     9.741961    10.39904
       d1627 |   9.944426   .1871487    53.14   0.000     9.577109    10.31174
       d1628 |   9.991987    .147954    67.53   0.000     9.701598    10.28238
       d1629 |   10.17852   .1307103    77.87   0.000     9.921979    10.43507
       d1630 |   10.07059   .1641402    61.35   0.000     9.748432    10.39275
       d1726 |   9.958317   .4832158    20.61   0.000     9.009909    10.90673
       d1727 |   10.04576   .2236854    44.91   0.000     9.606732    10.48479
       d1728 |   10.16565    .295908    34.35   0.000     9.584869    10.74643
       d1729 |   9.617564   .4184771    22.98   0.000     8.796218    10.43891
       d1730 |   10.01598   .3742973    26.76   0.000     9.281348    10.75061
------------------------------------------------------------------------------

.
. * Export the regression output in three separate fragments
. outreg2 using "p1a_1.tex", replace tex(fragment) label ctitle("lwage") dec(3)
>  keep(d1226 d1227 d1228 d1229 d1230 d1326 d1327 d1328 d1329 d1330) nonotes no
> obs nor2
p1a_1.tex
dir : seeout

. outreg2 using "p1a_2.tex", replace tex(fragment) label ctitle("lwage") dec(3)
>  keep(d1426 d1427 d1428 d1429 d1430 d1526 d1527 d1528 d1529 d1530)
p1a_2.tex
dir : seeout

. outreg2 using "p1a_3.tex", replace tex(fragment) label ctitle("lwage") dec(3)
>  keep(d1626 d1627 d1628 d1629 d1630 d1726 d1727 d1728 d1729 d1730) nonotes no
> obs nor2
p1a_3.tex
dir : seeout

.

\begin{landscape}
\begin{table}[!htbp]\centering
\caption{Regression of lwage on dummies for education and age}
\label{tab:problem1a}

\begin{subtable}[t]{0.32\textwidth}\centering
\begin{tabular}{lc} \hline
 & (1) \\
 & lwage \\ \hline
 &  \\
$I(\text{edu} = 12, \text{age} = 26)$ & 9.451*** \\
 & (0.091) \\
$I(\text{edu} = 12, \text{age} = 27)$ & 9.300*** \\
 & (0.085) \\
$I(\text{edu} = 12, \text{age} = 28)$ & 9.538*** \\
 & (0.083) \\
$I(\text{edu} = 12, \text{age} = 29)$ & 9.386*** \\
 & (0.085) \\
$I(\text{edu} = 12, \text{age} = 30)$ & 9.628*** \\
 & (0.088) \\
$I(\text{edu} = 13, \text{age} = 26)$ & 9.612*** \\
 & (0.192) \\
$I(\text{edu} = 13, \text{age} = 27)$ & 9.756*** \\
 & (0.192) \\
$I(\text{edu} = 13, \text{age} = 28)$ & 9.378*** \\
 & (0.175) \\
$I(\text{edu} = 13, \text{age} = 29)$ & 9.820*** \\
 & (0.224) \\
$I(\text{edu} = 13, \text{age} = 30)$ & 9.446*** \\
 & (0.203) \\

 & \\
 & \\
 & \\ \hline
 & \\
 & \\
\end{tabular}
\end{subtable}\hfill
\begin{subtable}[t]{0.32\textwidth}\centering
\begin{tabular}{lc} \hline
 & (1) \\
 & lwage \\ \hline
 &  \\
$I(\text{edu} = 14, \text{age} = 26)$ & 9.581*** \\
 & (0.224) \\
$I(\text{edu} = 14, \text{age} = 27)$ & 9.794*** \\
 & (0.171) \\
$I(\text{edu} = 14, \text{age} = 28)$ & 9.642*** \\
 & (0.216) \\
$I(\text{edu} = 14, \text{age} = 29)$ & 9.712*** \\
 & (0.175) \\
$I(\text{edu} = 14, \text{age} = 30)$ & 9.645*** \\
 & (0.171) \\
$I(\text{edu} = 15, \text{age} = 26)$ & 9.535*** \\
 & (0.242) \\
$I(\text{edu} = 15, \text{age} = 27)$ & 9.386*** \\
 & (0.232) \\
$I(\text{edu} = 15, \text{age} = 28)$ & 9.573*** \\
 & (0.265) \\
$I(\text{edu} = 15, \text{age} = 29)$ & 9.540*** \\
 & (0.252) \\
$I(\text{edu} = 15, \text{age} = 30)$ & 9.919*** \\
 & (0.242) \\
 &  \\
Observations & 898 \\
 R-squared & 0.993 \\ \hline
\multicolumn{2}{c}{ Standard errors in parentheses} \\
\multicolumn{2}{c}{ *** p$<$0.01, ** p$<$0.05, * p$<$0.1} \\
\end{tabular}


\end{subtable}\hfill
\begin{subtable}[t]{0.32\textwidth}\centering
\begin{tabular}{lc} \hline
 & (1) \\
 & lwage \\ \hline
 &  \\
$I(\text{edu} = 12, \text{age} = 26)$ & 9.451*** \\
 & (0.091) \\
$I(\text{edu} = 12, \text{age} = 27)$ & 9.300*** \\
 & (0.085) \\
$I(\text{edu} = 12, \text{age} = 28)$ & 9.538*** \\
 & (0.083) \\
$I(\text{edu} = 12, \text{age} = 29)$ & 9.386*** \\
 & (0.085) \\
$I(\text{edu} = 12, \text{age} = 30)$ & 9.628*** \\
 & (0.088) \\
$I(\text{edu} = 13, \text{age} = 26)$ & 9.612*** \\
 & (0.192) \\
$I(\text{edu} = 13, \text{age} = 27)$ & 9.756*** \\
 & (0.192) \\
$I(\text{edu} = 13, \text{age} = 28)$ & 9.378*** \\
 & (0.175) \\
$I(\text{edu} = 13, \text{age} = 29)$ & 9.820*** \\
 & (0.224) \\
$I(\text{edu} = 13, \text{age} = 30)$ & 9.446*** \\
 & (0.203) \\

 & \\
 & \\
 & \\ \hline
 & \\
 & \\
\end{tabular}
\end{subtable}

\end{table}
\end{landscape}

**Problem 1b**

Export R matrix as LaTeX table

In [40]:
# Obtain lists of unique education and age levels
edu_levels = sorted(set([int(col[1:3]) for col in dummies.columns.tolist()]))
age_levels = sorted(set([int(col[3:5]) for col in dummies.columns.tolist()]))

# Store the column names and indexes of the matrix 
colnames = [f'alpha{edu}{age}' for edu in edu_levels for age in age_levels]
collabels = [fr'$\alpha_{{{edu},{age}}}$' for e in edu_levels for a in age_levels]
idx = {name: i for i, name in enumerate(colnames)}

# Specify anchors 
anchors = {(12,26),(12,27),(13,26),(13,27)}

# Initialize lists of row names and rows
rownames, rows = [], []

for edu in edu_levels:
    for age in age_levels:
        if (edu, age) not in anchors:
            rownames.append(fr'$\alpha_{{{edu},{age}}}$' )
            row = np.zeros(len(colnames))
            row[idx[f'alpha{edu}{age}']] = 1
            row[idx['alpha1226']] = -1 + (edu-12) + (age-26) - (edu-12)*(age-26)
            row[idx['alpha1327']] = - (edu-12) + (edu-12)*(age-26)
            row[idx['alpha1227']] = - (age-26) + (edu-12)*(age-26)
            row[idx['alpha1327']] = - (edu-12)*(age-26)
            rows.append(row)

R=pd.DataFrame(np.asarray(rows, dtype=int), index=rownames, columns=collabels)
R.to_latex(
    buf="p1b.tex",
    index=False, header=True, escape=False,
    column_format='l' + 'c'*len(colnames),  # left row-label + numeric columns
)

Perform F test in STATA

In [43]:
# Build the joint restriction string in Python
tests = []
anchors = {(12,26), (12,27), (13,26), (13,27)}
for edu in edu_levels:
    for age in age_levels:
        if (edu, age) in anchors:
            continue
        r = edu - 12
        s = age - 26
        c1226 = -1 + (edu-12) + (age-26) - (edu-12)*(age-26)
        c1326 = -(edu-12) + (edu-12)*(age-26)
        c1227 = -(age-26) + (edu-12)*(age-26)
        c1327 = -(edu-12)*(age-26)
        expr = f'( d{edu}{age} + {c1226}*d1226 + {c1326}*d1326 + {c1227}*d1227 + {c1327}*d1327 = 0 )'
        tests.append(expr)

test_stmt = " ".join(tests)

# Run the unrestricted regression and F test in STATA
stata.pdataframe_to_data(ps1small, force=True)

stata.run(fr'''
* Unrestricted regression
regress log_wage {dummies_str} , nocons

* F test of all 26 restrictions:
test {test_stmt}
''')

.
. * Unrestricted regression
. regress log_wage d1226 d1227 d1228 d1229 d1230 d1326 d1327 d1328 d1329 d1330
> d1426 d1427 d1428 d1429 d1430 d1526 d1527 d1528 d1529 d1530 d1626 d1627 d1628
>  d1629 d1630 d1726 d1727 d1728 d1729 d1730 , nocons

      Source |       SS           df       MS      Number of obs   =       898
-------------+----------------------------------   F(30, 868)      =   3960.93
       Model |  83238.0973        30  2774.60324   Prob > F        =    0.0000
    Residual |  608.027447       868   .70049245   R-squared       =    0.9927
-------------+----------------------------------   Adj R-squared   =    0.9925
       Total |  83846.1247       898  93.3698493   Root MSE        =    .83695

------------------------------------------------------------------------------
    log_wage | Coefficient  Std. err.      t    P>|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
       d1226 |    9.45132   .0907804   104.11   0.000     9.273145    9.629495
       d1227 |   9.300426   .0849798   109.44   0.000     9.133636    9.467216
       d1228 |   9.537856   .0832801   114.53   0.000     9.374402     9.70131
       d1229 |   9.385826   .0854213   109.88   0.000      9.21817    9.553483
       d1230 |   9.628323   .0877366   109.74   0.000     9.456122    9.800524
       d1326 |    9.61212   .1920105    50.06   0.000     9.235261     9.98898
       d1327 |   9.755901   .1920105    50.81   0.000     9.379042    10.13276
       d1328 |   9.378158    .174517    53.74   0.000     9.035633    9.720683
       d1329 |   9.819982   .2236854    43.90   0.000     9.380955    10.25901
       d1330 |   9.446488   .2029912    46.54   0.000     9.048077    9.844899
       d1426 |   9.580658   .2236854    42.83   0.000      9.14163    10.01969
       d1427 |   9.794423   .1708426    57.33   0.000      9.45911    10.12974
       d1428 |   9.642237   .2161007    44.62   0.000     9.218096    10.06638
       d1429 |   9.712199    .174517    55.65   0.000     9.369674    10.05472
       d1430 |    9.64544   .1708426    56.46   0.000     9.310127    9.980753
       d1526 |   9.534555   .2416079    39.46   0.000     9.060351    10.00876
       d1527 |   9.385619   .2321293    40.43   0.000     8.930019     9.84122
       d1528 |   9.573155   .2646682    36.17   0.000      9.05369    10.09262
       d1529 |   9.540361   .2523512    37.81   0.000     9.045071    10.03565
       d1530 |   9.919473   .2416079    41.06   0.000     9.445269    10.39368
       d1626 |    10.0705   .1673909    60.16   0.000     9.741961    10.39904
       d1627 |   9.944426   .1871487    53.14   0.000     9.577109    10.31174
       d1628 |   9.991987    .147954    67.53   0.000     9.701598    10.28238
       d1629 |   10.17852   .1307103    77.87   0.000     9.921979    10.43507
       d1630 |   10.07059   .1641402    61.35   0.000     9.748432    10.39275
       d1726 |   9.958317   .4832158    20.61   0.000     9.009909    10.90673
       d1727 |   10.04576   .2236854    44.91   0.000     9.606732    10.48479
       d1728 |   10.16565    .295908    34.35   0.000     9.584869    10.74643
       d1729 |   9.617564   .4184771    22.98   0.000     8.796218    10.43891
       d1730 |   10.01598   .3742973    26.76   0.000     9.281348    10.75061
------------------------------------------------------------------------------

.
. * F test of all 26 restrictions:
. test ( d1228 + 1*d1226 + 0*d1326 + -2*d1227 + 0*d1327 = 0 ) ( d1229 + 2*d1226
>  + 0*d1326 + -3*d1227 + 0*d1327 = 0 ) ( d1230 + 3*d1226 + 0*d1326 + -4*d1227
> + 0*d1327 = 0 ) ( d1328 + 0*d1226 + 1*d1326 + 0*d1227 + -2*d1327 = 0 ) ( d132
> 9 + 0*d1226 + 2*d1326 + 0*d1227 + -3*d1327 = 0 ) ( d1330 + 0*d1226 + 3*d1326
> + 0*d1227 + -4*d1327 = 0 ) ( d1426 + 1*d1226 + -2*d1326 + 0*d1227 + 0*d1327 =
>  0 ) ( d1427 + 0*d1226 + 0*d1326 + 1*d1227 + -2*d1327 = 0 ) ( d1428 + -1*d122
> 6 + 2*d1326 + 2*d1227 + -4*d1327 = 0 ) ( d1429 + -2*d1226 + 4*d1326 + 3*d1227
>  + -6*d1327 = 0 ) ( d1430 + -3*d1226 + 6*d1326 + 4*d1227 + -8*d1327 = 0 ) ( d
> 1526 + 2*d1226 + -3*d1326 + 0*d1227 + 0*d1327 = 0 ) ( d1527 + 0*d1226 + 0*d13
> 26 + 2*d1227 + -3*d1327 = 0 ) ( d1528 + -2*d1226 + 3*d1326 + 4*d1227 + -6*d13
> 27 = 0 ) ( d1529 + -4*d1226 + 6*d1326 + 6*d1227 + -9*d1327 = 0 ) ( d1530 + -6
> *d1226 + 9*d1326 + 8*d1227 + -12*d1327 = 0 ) ( d1626 + 3*d1226 + -4*d1326 + 0
> *d1227 + 0*d1327 = 0 ) ( d1627 + 0*d1226 + 0*d1326 + 3*d1227 + -4*d1327 = 0 )
>  ( d1628 + -3*d1226 + 4*d1326 + 6*d1227 + -8*d1327 = 0 ) ( d1629 + -6*d1226 +
>  8*d1326 + 9*d1227 + -12*d1327 = 0 ) ( d1630 + -9*d1226 + 12*d1326 + 12*d1227
>  + -16*d1327 = 0 ) ( d1726 + 4*d1226 + -5*d1326 + 0*d1227 + 0*d1327 = 0 ) ( d
> 1727 + 0*d1226 + 0*d1326 + 4*d1227 + -5*d1327 = 0 ) ( d1728 + -4*d1226 + 5*d1
> 326 + 8*d1227 + -10*d1327 = 0 ) ( d1729 + -8*d1226 + 10*d1326 + 12*d1227 + -1
> 5*d1327 = 0 ) ( d1730 + -12*d1226 + 15*d1326 + 16*d1227 + -20*d1327 = 0 )

 ( 1)  d1226 - 2*d1227 + d1228 = 0
 ( 2)  2*d1226 - 3*d1227 + d1229 = 0
 ( 3)  3*d1226 - 4*d1227 + d1230 = 0
 ( 4)  d1326 - 2*d1327 + d1328 = 0
 ( 5)  2*d1326 - 3*d1327 + d1329 = 0
 ( 6)  3*d1326 - 4*d1327 + d1330 = 0
 ( 7)  d1226 - 2*d1326 + d1426 = 0
 ( 8)  d1227 - 2*d1327 + d1427 = 0
 ( 9)  - d1226 + 2*d1227 + 2*d1326 - 4*d1327 + d1428 = 0
 (10)  - 2*d1226 + 3*d1227 + 4*d1326 - 6*d1327 + d1429 = 0
 (11)  - 3*d1226 + 4*d1227 + 6*d1326 - 8*d1327 + d1430 = 0
 (12)  2*d1226 - 3*d1326 + d1526 = 0
 (13)  2*d1227 - 3*d1327 + d1527 = 0
 (14)  - 2*d1226 + 4*d1227 + 3*d1326 - 6*d1327 + d1528 = 0
 (15)  - 4*d1226 + 6*d1227 + 6*d1326 - 9*d1327 + d1529 = 0
 (16)  - 6*d1226 + 8*d1227 + 9*d1326 - 12*d1327 + d1530 = 0
 (17)  3*d1226 - 4*d1326 + d1626 = 0
 (18)  3*d1227 - 4*d1327 + d1627 = 0
 (19)  - 3*d1226 + 6*d1227 + 4*d1326 - 8*d1327 + d1628 = 0
 (20)  - 6*d1226 + 9*d1227 + 8*d1326 - 12*d1327 + d1629 = 0
 (21)  - 9*d1226 + 12*d1227 + 12*d1326 - 16*d1327 + d1630 = 0
 (22)  4*d1226 - 5*d1326 + d1726 = 0
 (23)  4*d1227 - 5*d1327 + d1727 = 0
 (24)  - 4*d1226 + 8*d1227 + 5*d1326 - 10*d1327 + d1728 = 0
 (25)  - 8*d1226 + 12*d1227 + 10*d1326 - 15*d1327 + d1729 = 0
 (26)  - 12*d1226 + 16*d1227 + 15*d1326 - 20*d1327 + d1730 = 0

       F( 26,   868) =    0.92
            Prob > F =    0.5806

.